# Generated by Django 2.1.7 on 2019-05-01 22:11

from django.db import migrations, models
import email_gen.models.cloud_storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceListFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=email_gen.models.cloud_storage.CloudStorage(), upload_to='')),
                ('list_type', models.CharField(default='retx', editable=False, max_length=4)),
                ('display_name', models.CharField(default='Real Estate - TX', editable=False, max_length=30)),
            ],
        ),
    ]
