# Generated by Django 2.2.1 on 2019-05-11 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=180)),
                ('firstname', models.CharField(blank=True, max_length=60)),
                ('middlename', models.CharField(blank=True, max_length=60)),
                ('lastname', models.CharField(blank=True, max_length=60)),
                ('suffix', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SourceListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=60)),
                ('display_name', models.CharField(default='Uploaded List', max_length=60)),
                ('update_date', models.DateField(auto_now=True)),
                ('field_labels', models.CharField(blank=True, max_length=1000)),
                ('field_types', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TextAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_label', models.CharField(default='text_field', max_length=32)),
                ('text', models.CharField(max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_fields', to='email_gen.Person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='source_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='email_gen.SourceListModel'),
        ),
        migrations.CreateModel(
            name='NumericAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_label', models.CharField(default='numeric_field', max_length=32)),
                ('num', models.IntegerField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='num_fields', to='email_gen.Person')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_label', models.CharField(default='email', max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='email_gen.Person')),
            ],
        ),
        migrations.CreateModel(
            name='DateAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_label', models.CharField(default='date_field', max_length=32)),
                ('date', models.DateField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_fields', to='email_gen.Person')),
            ],
        ),
    ]
