# Generated by Django 2.1.7 on 2019-05-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcelistfilemodel',
            name='file',
        ),
        migrations.AddField(
            model_name='sourcelistfilemodel',
            name='file_name',
            field=models.CharField(default='retx', max_length=40),
        ),
    ]
