# Generated by Django 2.1.7 on 2019-05-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisertexas',
            name='mail_3',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
