# Generated by Django 2.1.7 on 2019-05-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0002_auto_20190502_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisertexas',
            name='mail_state',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
