# Generated by Django 2.2.1 on 2019-05-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0003_auto_20190514_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='lic_exp',
            new_name='lic_date_exp',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='lic_date',
            new_name='lic_date_orig',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='trec_app_expires',
            new_name='trec_date_app_expires',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='trec_app_received',
            new_name='trec_date_app_received',
        ),
    ]
