# Generated by Django 2.1.7 on 2019-05-02 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0004_auto_20190502_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisertexas',
            name='source_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='email_gen.AppraiserTexasListModel'),
        ),
    ]
