# Generated by Django 2.1.7 on 2019-05-03 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0005_auto_20190502_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateAgentTexasModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lic_type', models.CharField(choices=[('SALE', 'Sales Agent'), ('BRK', 'Individual Broker'), ('BLLC', 'Limited Liability Corporation Broker'), ('BCRP', 'Corporation Broker'), ('6', 'Partnership Broker'), ('REB', 'Broker Organization Branch'), ('PRIN', 'Professional Inspector'), ('REIN', 'Real Estate Inspector'), ('APIN', 'Apprentice Inspector'), ('ILLC', 'Professional Inspector, LLC'), ('ICRP', 'Professional Inspector, Corporation'), ('ERWI', 'Easement and Right-of-Way, Individual'), ('ERWO', 'Easement and Right-of-Way, Business')], max_length=4)),
                ('lic_num', models.PositiveIntegerField()),
                ('full_name', models.CharField(max_length=40)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('lic_status', models.PositiveSmallIntegerField(choices=[('20', 'Current and Active'), ('21', 'Current and Inactive'), ('30', 'Probation and Active'), ('31', 'Probation and Inactive'), ('45', 'Expired'), ('47', 'Suspended'), ('56', 'Relinquished'), ('57', 'Revoked'), ('80', 'Deceased')])),
                ('lic_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('ed_status', models.CharField(choices=[('0', 'No Non-elective CE Requirement'), ('1', 'Non-elective CE Requirements Outstanding'), ('2', 'Non-elective CE Requirements Met')], max_length=3)),
                ('mce_status', models.CharField(choices=[('0', 'No MCE Requirement'), ('1', 'MCE Requirements Outstanding'), ('2', 'MCE Requirements Met')], max_length=3)),
                ('des_supervisor', models.CharField(max_length=3)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mail_1', models.CharField(blank=True, max_length=60)),
                ('mail_2', models.CharField(blank=True, max_length=60)),
                ('mail_3', models.CharField(blank=True, max_length=60)),
                ('mail_city', models.CharField(blank=True, max_length=60)),
                ('mail_state', models.CharField(blank=True, max_length=4)),
                ('mail_zip', models.CharField(blank=True, max_length=12)),
                ('mail_county', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateTexasListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(default='aptx', editable=False, max_length=4)),
                ('display_name', models.CharField(default='Appraisal - Texas', editable=False, max_length=30)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='AppraiserTexas',
            new_name='AppraiserTexasModel',
        ),
        migrations.AddField(
            model_name='realestateagenttexasmodel',
            name='source_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='email_gen.RealEstateTexasListModel'),
        ),
    ]
