# Generated by Django 2.2.1 on 2019-05-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0005_auto_20190514_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='county',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='fullname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='lic_status',
            field=models.CharField(choices=[('N/A', 'Not Available'), ('ACT', 'Active'), ('INA', 'Inactive'), ('EXP', 'Expired'), ('SUS', 'Suspended'), ('REL', 'Relinquished'), ('REV', 'Revoked'), ('DEC', 'Deceased')], default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='lic_type',
            field=models.CharField(choices=[('SALE', 'TREC - Sales Agent'), ('BRK', 'TREC - Individual Broker'), ('BLLC', 'TREC - Limited Liability Corporation Broker'), ('BCRP', 'TREC - Corporation Broker'), ('6', 'TREC - Partnership Broker'), ('REB', 'TREC - Broker Organization Branch'), ('PRIN', 'TREC - Professional Inspector'), ('REIN', 'TREC - Real Estate Inspector'), ('APIN', 'TREC - Apprentice Inspector'), ('ILLC', 'TREC - Professional Inspector, LLC'), ('ICRP', 'TREC - Professional Inspector, Corporation'), ('ERWI', 'TREC - Easement and Right-of-Way, Individual'), ('ERWO', 'TREC - Easement and Right-of-Way, Business'), ('APCR', 'TALCB - Certified Residential Appraiser'), ('APGN', 'TALCB - Certified General Appraiser'), ('APOS', 'TALCB - Temporary Out of State Appraiser'), ('APPV', 'TALCB - Provisional Licensed Appraiser'), ('APSC', 'TALCB - Licensed Residential Appraiser'), ('APTR', 'TALCB - Appraiser Trainee'), ('BR', 'OREC - Broker'), ('SA', 'OREC - Sales Associate'), ('PS', 'OREC - Provisional Sales Associate')], default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='middlename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='suffix',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='trec_ed_status',
            field=models.CharField(blank=True, choices=[('0', 'No Non-elective CE Requirement'), ('1', 'Non-elective CE Requirements Outstanding'), ('2', 'Non-elective CE Requirements Met')], default='n/a', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='trec_mce_status',
            field=models.CharField(blank=True, choices=[('0', 'No MCE Requirement'), ('1', 'MCE Requirements Outstanding'), ('2', 'MCE Requirements Met')], default='n/a', max_length=255),
        ),
    ]
