# Generated by Django 2.1.7 on 2019-05-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0006_auto_20190502_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisertexasmodel',
            name='agency_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='appraisertexasmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='appraisertexasmodel',
            name='mail_1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='appraisertexasmodel',
            name='mail_2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='appraisertexasmodel',
            name='mail_3',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='appraisertexasmodel',
            name='mail_city',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='appraisertexasmodel',
            name='mail_county',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='appraisertexasmodel',
            name='mail_state',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='appraisertexasmodel',
            name='mail_zip',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='appraisertexasmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appraisertexasmodel',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='realestateagenttexasmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='realestateagenttexasmodel',
            name='mail_1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='realestateagenttexasmodel',
            name='mail_2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='realestateagenttexasmodel',
            name='mail_3',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='realestateagenttexasmodel',
            name='mail_city',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='realestateagenttexasmodel',
            name='mail_county',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='realestateagenttexasmodel',
            name='mail_state',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='realestateagenttexasmodel',
            name='mail_zip',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='realestateagenttexasmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='realestateagenttexasmodel',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
