# Generated by Django 2.1.7 on 2019-05-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0007_auto_20190503_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisertexaslistmodel',
            name='upload_date',
        ),
        migrations.AlterField(
            model_name='appraisertexaslistmodel',
            name='update_date',
            field=models.DateTimeField(),
        ),
    ]
