# Generated by Django 2.1.7 on 2019-05-04 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0008_auto_20190503_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateTexasPrepListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(default='retxprep', editable=False, max_length=4)),
                ('display_name', models.CharField(default='Real Estate License Applications - Texas', editable=False, max_length=30)),
                ('update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateTexasPrepModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=16)),
                ('lic_type', models.CharField(max_length=6)),
                ('app_received', models.DateField()),
                ('exp_date', models.DateField()),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('suffix', models.CharField(max_length=20)),
                ('mail_1', models.CharField(blank=True, max_length=60, null=True)),
                ('mail_2', models.CharField(blank=True, max_length=60, null=True)),
                ('mail_3', models.CharField(blank=True, max_length=60, null=True)),
                ('mail_city', models.CharField(blank=True, max_length=60, null=True)),
                ('mail_state', models.CharField(blank=True, max_length=4, null=True)),
                ('mail_zip', models.CharField(blank=True, max_length=12, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('completed_prelicense', models.CharField(max_length=3)),
                ('completed_sae', models.CharField(max_length=3)),
                ('completed_broker', models.CharField(max_length=3)),
                ('source_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='email_gen.RealEstateTexasPrepListModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='realestatetexaslistmodel',
            name='upload_date',
        ),
        migrations.AlterField(
            model_name='realestatetexaslistmodel',
            name='display_name',
            field=models.CharField(default='Real Estate - Texas', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='realestatetexaslistmodel',
            name='list_type',
            field=models.CharField(default='retx', editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='realestatetexaslistmodel',
            name='update_date',
            field=models.DateTimeField(),
        ),
    ]
