# Generated by Django 2.1.7 on 2019-05-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0009_auto_20190503_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatetexasprepmodel',
            name='street_num',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
