# Generated by Django 2.2.1 on 2019-05-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0010_auto_20190516_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='designated_supervisor',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
