# Generated by Django 2.1.7 on 2019-05-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0010_realestatetexasprepmodel_street_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatetexaspreplistmodel',
            name='list_type',
            field=models.CharField(default='retxprep', editable=False, max_length=8),
        ),
    ]
