# Generated by Django 2.2.1 on 2019-05-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0011_auto_20190517_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='designated_supervisor',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='trec_ed_status',
            field=models.CharField(blank=True, choices=[('0', 'No Non-elective CE Requirement'), ('1', 'Non-elective CE Requirements Outstanding'), ('2', 'Non-elective CE Requirements Met')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='trec_mce_status',
            field=models.CharField(blank=True, choices=[('0', 'No MCE Requirement'), ('1', 'MCE Requirements Outstanding'), ('2', 'MCE Requirements Met')], max_length=255, null=True),
        ),
    ]
