# Generated by Django 2.1.7 on 2019-05-05 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0012_auto_20190503_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='NumericAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=180)),
                ('firstname', models.CharField(blank=True, max_length=60)),
                ('middlename', models.CharField(blank=True, max_length=60)),
                ('lastname', models.CharField(blank=True, max_length=60)),
                ('suffix', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SourceListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=60)),
                ('display_name', models.CharField(max_length=60)),
                ('update_date', models.DateField(auto_now=True)),
                ('field_labels', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TextAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_gen.Person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='source_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='email_gen.SourceListModel'),
        ),
        migrations.AddField(
            model_name='numericattribute',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_gen.Person'),
        ),
        migrations.AddField(
            model_name='emailattribute',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_gen.Person'),
        ),
        migrations.AddField(
            model_name='dateattribute',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_gen.Person'),
        ),
    ]
