# Generated by Django 2.2.1 on 2019-05-25 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0012_auto_20190517_2144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
