# Generated by Django 2.1.7 on 2019-05-05 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0013_auto_20190504_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateattribute',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailattribute',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='numericattribute',
            name='num',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
