# Generated by Django 2.2.1 on 2019-05-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0013_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcelistmodel',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcelistmodel',
            name='field_labels',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
