# Generated by Django 2.2.1 on 2019-05-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0015_inspectortexas_realestatesalesagentapplicanttexas_realestatesalesagenttexas_texasappraiser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcelistmodel',
            old_name='file_name',
            new_name='file_id',
        ),
        migrations.AddField(
            model_name='sourcelistmodel',
            name='zip_file_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
