# Generated by Django 2.1.7 on 2019-05-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0016_auto_20190505_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateattribute',
            name='field_label',
            field=models.CharField(default='date_field', max_length=32),
        ),
        migrations.AddField(
            model_name='emailattribute',
            name='field_label',
            field=models.CharField(default='email', max_length=32),
        ),
        migrations.AddField(
            model_name='numericattribute',
            name='field_label',
            field=models.CharField(default='numeric_field', max_length=32),
        ),
        migrations.AddField(
            model_name='textattribute',
            name='field_label',
            field=models.CharField(default='text_field', max_length=32),
        ),
    ]
