# Generated by Django 2.2.1 on 2019-05-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0016_auto_20190525_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestatesalesagentapplicanttexas',
            name='source_list',
        ),
        migrations.RemoveField(
            model_name='realestatesalesagenttexas',
            name='source_list',
        ),
        migrations.RemoveField(
            model_name='texasappraiser',
            name='source_list',
        ),
        migrations.AlterField(
            model_name='sourcelistmodel',
            name='field_labels',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sourcelistmodel',
            name='file_id',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.DeleteModel(
            name='InspectorTexas',
        ),
        migrations.DeleteModel(
            name='RealEstateSalesAgentApplicantTexas',
        ),
        migrations.DeleteModel(
            name='RealEstateSalesAgentTexas',
        ),
        migrations.DeleteModel(
            name='TexasAppraiser',
        ),
    ]
