# Generated by Django 2.1.7 on 2019-05-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0017_auto_20190505_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcelistmodel',
            old_name='short_name',
            new_name='file_name',
        ),
        migrations.AlterField(
            model_name='sourcelistmodel',
            name='display_name',
            field=models.CharField(default='Uploaded List', max_length=60),
        ),
        migrations.AlterField(
            model_name='sourcelistmodel',
            name='field_labels',
            field=models.TextField(blank=True),
        ),
    ]
