# Generated by Django 2.1.7 on 2019-05-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0018_auto_20190505_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcelistmodel',
            name='field_types',
            field=models.TextField(blank=True),
        ),
    ]
