# Generated by Django 2.2.1 on 2019-05-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0018_appraisertexas_inspectortexas_realestatesalesagentapplicanttexas_realestatesalesagenttexas'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectortexas',
            name='designated_supervisor',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
