# Generated by Django 2.2.1 on 2019-05-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0019_inspectortexas_designated_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisertexas',
            name='trec_county',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='inspectortexas',
            name='trec_county',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='realestatesalesagenttexas',
            name='trec_county',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
