# Generated by Django 2.1.7 on 2019-05-08 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0019_sourcelistmodel_field_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateattribute',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_fields', to='email_gen.Person'),
        ),
        migrations.AlterField(
            model_name='emailattribute',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='email_gen.Person'),
        ),
        migrations.AlterField(
            model_name='numericattribute',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='num_fields', to='email_gen.Person'),
        ),
        migrations.AlterField(
            model_name='textattribute',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_fields', to='email_gen.Person'),
        ),
    ]
