# Generated by Django 2.1.7 on 2019-05-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0020_auto_20190507_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcelistmodel',
            name='field_labels',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='sourcelistmodel',
            name='field_types',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
