# Generated by Django 2.2.1 on 2019-05-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0020_auto_20190526_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisertexas',
            name='trec_county',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectortexas',
            name='trec_county',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realestatesalesagenttexas',
            name='trec_county',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
