# Generated by Django 2.2.2 on 2019-06-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0022_sourcelistmodel_expected_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcelistmodel',
            name='encoding',
            field=models.CharField(default='latin', max_length=30),
        ),
    ]
