# Generated by Django 2.2.2 on 2019-06-19 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_gen', '0025_realestatesalesagentoklahoma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcelistmodel',
            name='encoding',
        ),
    ]
